FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine-openjdk:8

WORKDIR /usr/src

RUN apk add --no-cache python3 py3-pip wget

RUN wget -q "https://github.com/blynkkk/blynk-server/releases/download/v0.41.16/server-0.41.16-java8.jar"

COPY . /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]